apiVersion: v1
kind: Namespace
metadata:
  name: olm-console-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-console-plugin
  namespace: olm-console-plugin
  labels:
    app: olm-console-plugin
    app.kubernetes.io/component: olm-console-plugin
    app.kubernetes.io/part-of: olm-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olm-console-plugin
  template:
    metadata:
      labels:
        app: olm-console-plugin
    spec:
      containers:
        - name: olm-console-plugin
          image: quay.io/openshift/olm-console-plugin:latest
          ports:
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: olm-console-plugin
  namespace: olm-console-plugin
  labels:
    app: olm-console-plugin
    app.kubernetes.io/component: olm-console-plugin
    app.kubernetes.io/part-of: olm-console-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: olm-console-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: olm-console-plugin
spec:
  backend:
    type: Service
    service:
      name: olm-console-plugin
      namespace: olm-console-plugin
      port: 9001
      basePath: /
  displayName: Operator Lifecycle Manager
  i18n:
    loadType: Preload
